# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optimized_build_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1doptimized_build_metrics.proto\"\xb1\x04\n\x15OptimizedBuildMetrics\x12\x1a\n\ranalysis_time\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x17\n\nbuild_time\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x1b\n\x0epackaging_time\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x46\n\rtarget_result\x18\x04 \x03(\x0b\x32/.OptimizedBuildMetrics.TargetOptimizationResult\x1a\xc9\x02\n\x18TargetOptimizationResult\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\toptimized\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x1b\n\x0epackaging_time\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12W\n\x0foutput_artifact\x18\x04 \x03(\x0b\x32>.OptimizedBuildMetrics.TargetOptimizationResult.OutputArtifact\x1a\x62\n\x0eOutputArtifact\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04size\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x18\n\x10included_modules\x18\x03 \x03(\tB\x07\n\x05_nameB\x07\n\x05_sizeB\x07\n\x05_nameB\x0c\n\n_optimizedB\x11\n\x0f_packaging_timeB\x10\n\x0e_analysis_timeB\r\n\x0b_build_timeB\x11\n\x0f_packaging_timeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimized_build_metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIMIZEDBUILDMETRICS._serialized_start=34
  _OPTIMIZEDBUILDMETRICS._serialized_end=595
  _OPTIMIZEDBUILDMETRICS_TARGETOPTIMIZATIONRESULT._serialized_start=214
  _OPTIMIZEDBUILDMETRICS_TARGETOPTIMIZATIONRESULT._serialized_end=543
  _OPTIMIZEDBUILDMETRICS_TARGETOPTIMIZATIONRESULT_OUTPUTARTIFACT._serialized_start=403
  _OPTIMIZEDBUILDMETRICS_TARGETOPTIMIZATIONRESULT_OUTPUTARTIFACT._serialized_end=501
# @@protoc_insertion_point(module_scope)
